# Project
mod_version=1.0.0
group=org.cyclops.integratedterminalscompat
java_version=21

# Common
minecraft_version=1.21.1
mod_name=IntegratedTerminals-Compat
mod_author=rubensworks (aka kroeser)
mod_id=integratedterminalscompat
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedTerminals-Compat
issue_tracker_url=https://github.com/CyclopsMC/IntegratedTerminals-Compat/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-terminals
description=Integrated Terminals compatibility with other mods. This mod is automatically packaged with Integrated Terminals.

parchment_version=2024.07.07
parchment_minecraft_version=1.21

# NeoForge
neoforge_version=21.1.2
neoforge_loader_version_range=[4,)

# Dependencies
cyclopscore_version=1.25.1-627
integrateddynamics_version=1.24.1-1004
integratedterminals_version=1.6.5-417
commoncapabilities_version=2.9.3-147
curios_version=7.3.4+1.20.4
jei_version=1.21-neoforge:19.5.0.31
emi_version=1.1.16+1.21.1
rei_version=16.0.783
cloth_config_version=15.0.140
architectury_version=13.0.6
