modLoader="javafml"
loaderVersion="[31.2,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTerminals-Compat/issues"
[[mods]]
modId="integratedterminalscompat"
version="${file.jarVersion}"
displayName="IntegratedTerminalsCompat"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-terminals"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
description='''
Integrated Terminals compatibility with other mods. This mod is automatically packaged with Integrated Terminals.
'''
[[dependencies.integratedterminalscompat]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.8.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.1.14,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.5.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="integratedterminals"
    mandatory=true
    versionRange="[1.0.14,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
