modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTerminals-Compat/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-terminals"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedterminalscompat"
version="${file.jarVersion}"
displayName="IntegratedTerminalsCompat"
description='''
Integrated Terminals compatibility with other mods. This mod is automatically packaged with Integrated Terminals.
'''
[[dependencies.integratedterminalscompat]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.14.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.10.13,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.8.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="integratedterminals"
    mandatory=true
    versionRange="[1.2.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,]"
    ordering="NONE"
    side="BOTH"
