modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedTerminals-Compat/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-terminals"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedterminalscompat"
version="${file.jarVersion}"
displayName="IntegratedTerminalsCompat"
description='''
Integrated Terminals compatibility with other mods. This mod is automatically packaged with Integrated Terminals.
'''
[[dependencies.integratedterminalscompat]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.11,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="integrateddynamics"
    type="required"
    versionRange="[1.23.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="commoncapabilities"
    type="required"
    versionRange="[2.9.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="integratedterminals"
    type="required"
    versionRange="[1.3.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedterminalscompat]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,]"
    ordering="NONE"
    side="BOTH"
